export default {
  START_LOADING: 'START_LOADING',
  COMPLETE_LOADING: 'COMPLETE_LOADING',
  RECEIVED_TWEETS: 'RECEIVED_TWEETS',

  CHANGE_SORTING_CURRENT_CONDITION: 'CHANGE_SORTING_CURRENT_CONDITION',
  CHANGE_SORTING_CURRENT_ORDER: 'CHANGE_SORTING_CURRENT_ORDER',
  SORTED_TWEETS: 'SORTED_TWEETS',

  CHANGE_FILTER_CURRENT_CONDITION: 'CHANGE_FILTER_CURRENT_CONDITION',
  CHANGE_FILTER_CURRENT_OPERATOR: 'CHANGE_FILTER_CURRENT_OPERATOR',
  CHANGE_FILTER_CURRENT_VALUE: 'CHANGE_FILTER_CURRENT_VALUE',
  FILTER_TWEETS: 'FILTER_TWEETS',
};
