export default {
  START_LOADING: 'START_LOADING',
  COMPLETE_LOADING: 'COMPLETE_LOADING',
  RECEIVED_TWEETS: 'RECEIVED_TWEETS',

  CHANGE_SORTING_CURRENT_CONDITION: 'CHANGE_SORTING_CURRENT_CONDITION',
  CHANGE_SORTING_CURRENT_ORDER: 'CHANGE_SORTING_CURRENT_ORDER',
  SORTED_TWEETS: 'SORTED_TWEETS',
};
